"use client";
import { Lato } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";

const lato = Lato({
  weight: ["100", "300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

// export const metadata = {
//   title: 'Royale touche',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(() => {
    console.log(window);
    window.dataLayer = window.dataLayer || [];
    function gtag() {
      dataLayer.push(arguments);
    }
    gtag("js", new Date());

    gtag("config", "G-MTKLKTNEJT");
  });
  return (
    <html lang="en">
      <head>
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-MTKLKTNEJT"
        ></script>
      </head>

      <body className={lato.className}>{children}</body>
    </html>
  );
}
