
import { Lato } from 'next/font/google'
import './globals.css'

const lato = Lato({
  weight:['100','300','400','700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Royal touch',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className}>{children}
      </body>
    </html>
  )
}
